repos:
  - repo: local
    hooks:
      - id: ruff-format
        language: python
        name: ruff-format
        pass_filenames: false
        language_version: python3.12
        entry: uv run ruff format python/fastapi_radixer benchmarks

  - repo: local
    hooks:
      - id: ruff
        language: python
        name: ruff
        pass_filenames: false
        language_version: python3.12
        entry: uv run ruff check --fix --exit-non-zero-on-fix --show-fixes python/fastapi_radixer

  - repo: local
    hooks:
      - id: ty
        language: python
        name: ty
        pass_filenames: false
        entry: uv run ty check python/fastapi_radixer
