name: Benchmark

on:
  push:
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        python-version: [ 3.12, 3.13 ]

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: cache rust
        uses: Swatinem/rust-cache@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: dev
          args: --release
          sccache: true

      - name: Run benchmarks
        env:
          COLUMNS: 180
        run: |
          uv run python -m benchmarks.runner
